import { Inter } from 'next/font/google';
import type { Metadata } from 'next'

import './globals.css'
import { cn } from '@/lib/utils'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Hippo UI',
  description: 'Generated by Arik Alexandrov',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className='h-full'>
      <body className={cn('relative h-full font-sans antialiased', inter.className)}>
        <main className='flex flex-col relative min-h-screen'>
          <div className='flex-grow flex-1'>
        {children}

          </div>
       </main>
      </body>
    </html>
  )
}
